name: Composer Install

on:
  workflow_call:
    inputs:
      php_version:
        description: 'PHP version to use'
        required: false
        default: '8.0'

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php_version }}
          extensions: mbstring, intl

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: composer-cache-${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-cache-${{ runner.os }}-

      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist
