# The name of the Github Action that displays in github.com/<username>/<repo>/actions
name: Deploy to WordPress.org Repository

on:
  release:
    types: [released]

jobs:
  tag:
    name: New release
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Composer dependencies
      uses: php-actions/composer@v6
      with:
        dev: no
        php_version: 8.0

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Build assets
      run: |
        npm install
        npm run wps:build

    - name: WordPress Plugin Deploy
      id: deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      with:
        generate-zip: true

      env:
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}

    # After the deploy, we also want to create a zip and upload it to the release on Github. We don't want
    # users to have to go to the repository to find our plugin :).
    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        # Note, this is an exception to action secrets: GH_TOKEN is always available and provides access to
        # the current repository this action runs in.
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ steps.deploy.outputs.zip-path }}
        asset_name: aikon-role-manager.zip
        asset_content_type: application/zip
