name: PHP CI

on:
  push:
    paths:
      - '**/*.php'
  pull_request:
    paths:
      - '**/*.php'

permissions:
  contents: read

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install Composer dependencies
      uses: "ramsey/composer-install@v3"

    - name: Run PHP-CS-Fixer
      run: composer phpcs:check

    - name: Run Rector
      run: composer rector

    - name: Run PHPStan
      run: composer phpstan
