name: PHP-CS-Fixer

on:
  push:
    paths:
      - '**/*.php'
  pull_request:
    paths:
      - '**/*.php'

jobs:
  cs-fixer:
    uses: ./.github/workflows/composer-install.yml
    with:
      php_version: '8.0'
    steps:
      - name: Run PHP-CS-Fixer
        run: vendor/bin/php-cs-fixer fix --dry-run --diff
