name: PHPStan

on:
  push:
    paths:
      - '**/*.php'
  pull_request:
    paths:
      - '**/*.php'

jobs:
  phpstan:
    uses: ./.github/workflows/composer-install.yml
    with:
      php_version: '8.0'
    steps:
      - name: Run PHPStan
        run: vendor/bin/phpstan analyse src tests
