name: Rector

on:
  push:
    paths:
      - '**/*.php'
  pull_request:
    paths:
      - '**/*.php'

jobs:
  rector:
    uses: ./.github/workflows/composer-install.yml
    with:
      php_version: '8.0'
    steps:
      - name: Run Rector
        run: vendor/bin/rector process src
